# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-11 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20180511_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='audio',
            field=models.FilePathField(path='/home/dev/connectus/media/uploads/testupload'),
        ),
    ]
